// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS-iDIqVBOrkP2Zeaz7MF27Qrobn2j1A4',
    appId: '1:308219153821:web:3aeacbb7001ff9b7db3374',
    messagingSenderId: '308219153821',
    projectId: 'fir-test2-61388',
    authDomain: 'fir-test2-61388.firebaseapp.com',
    storageBucket: 'fir-test2-61388.firebasestorage.app',
    measurementId: 'G-BZT5BT1WB6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw8AoQ_DttjSVS-Dr_2zembk11_8KcDZQ',
    appId: '1:308219153821:android:d6279bb38430539fdb3374',
    messagingSenderId: '308219153821',
    projectId: 'fir-test2-61388',
    storageBucket: 'fir-test2-61388.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzGL8rb-RtHHLZe0DC-26D6BVs4me7Ink',
    appId: '1:308219153821:ios:31227c91a3be38b8db3374',
    messagingSenderId: '308219153821',
    projectId: 'fir-test2-61388',
    storageBucket: 'fir-test2-61388.firebasestorage.app',
    iosBundleId: 'com.example.firebaseTest2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzGL8rb-RtHHLZe0DC-26D6BVs4me7Ink',
    appId: '1:308219153821:ios:31227c91a3be38b8db3374',
    messagingSenderId: '308219153821',
    projectId: 'fir-test2-61388',
    storageBucket: 'fir-test2-61388.firebasestorage.app',
    iosBundleId: 'com.example.firebaseTest2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBS-iDIqVBOrkP2Zeaz7MF27Qrobn2j1A4',
    appId: '1:308219153821:web:262f699105cd7903db3374',
    messagingSenderId: '308219153821',
    projectId: 'fir-test2-61388',
    authDomain: 'fir-test2-61388.firebaseapp.com',
    storageBucket: 'fir-test2-61388.firebasestorage.app',
    measurementId: 'G-JBWB009WLZ',
  );
}
