name: Flutter CI

on:
  push:
    branches: [ main, dev ]  # Triggers on pushes to main/dev
  pull_request:
    branches: [ main ]       # Triggers on PRs to main

jobs:
  test:
    runs-on: ubuntu-latest
    
    # Set default working directory for all steps
    defaults:
      run:
        working-directory: ./Flutter_GrinNet

    steps:
      # 1. Checkout repository
      - uses: actions/checkout@v4

      # 2. Set up Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'  # Uses latest stable Flutter SDK

      # 3. Install dependencies (runs in ./flutter_app)
      - run: flutter pub get

      # 4. Run tests (all commands inherit working-directory)
      - run: flutter test           # Unit/widget tests
      - run: flutter test integration_test/  # Integration tests
      - run: flutter analyze        # Static analysis
      - run: flutter format --set-exit-if-changed .  # Format check
